# Generated by Django 5.1.2 on 2024-10-15 09:01

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_sell',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین فروش'),
        ),
    ]
