# Generated by Django 5.1.2 on 2024-10-15 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=75, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
