# Generated by Django 5.1.2 on 2024-10-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
    ]
