# Generated by Django 5.1.2 on 2024-10-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_last_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_sell',
        ),
    ]
