# Generated by Django 5.1.2 on 2024-10-15 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_last_sell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='نمایش در سایت'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'created_at'], name='product_idx'),
        ),
    ]
