# Generated by Django 5.1.2 on 2024-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_icon_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت جدید'),
        ),
    ]
