# Generated by Django 5.1.2 on 2025-01-21 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_new_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notify_me',
            field=models.ManyToManyField(blank=True, related_name='notify_me', to=settings.AUTH_USER_MODEL, verbose_name='به من اطلاع بده'),
        ),
    ]
