# Generated by Django 5.1.2 on 2024-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('is_visible', models.BooleanField(verbose_name='نمایش در سایت')),
            ],
        ),
    ]
