# Generated by Django 5.1.2 on 2024-10-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
    ]
