# Generated by Django 5.1.2 on 2024-10-15 19:53

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('برای سفارش', 'برای سفارش'), ('بازگشت وجه', 'بازگشت وجه')], max_length=21, verbose_name='علت تراکنش')),
                ('status', models.CharField(choices=[('پرداخت موفق', 'Paid'), ('پرداخت ناموفق', 'Failed')], max_length=21, verbose_name='وضعیت تراکنش')),
                ('description', models.TextField(max_length=100, verbose_name='توضیحات نراکنش')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='هزینه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ('created_at',),
            },
        ),
    ]
