# Generated by Django 5.1.2 on 2024-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پرداخت موفق', 'پرداخت موفق'), ('پرداخت ناموفق', 'پرداخت ناموفق')], max_length=21, verbose_name='وضعیت تراکنش'),
        ),
    ]
