# Generated by Django 5.1.2 on 2024-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_description',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='توضیحات اضافه'),
        ),
    ]
