# Generated by Django 5.1.2 on 2024-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(verbose_name='توضیحات نراکنش'),
        ),
    ]
